### ISSUE TITLE
Date formatting incorrect

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [williamhjcho/i18next#14]
I'm running the example app. In this app the date is not formatted:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/4954611/215444704-db41f127-77b2-41de-b784-163c11e33a7b.png">

I then saw in the readme that the dates can be formatted with `{{date, datetime(format:dd/MM/yyyy)}}`, this however does not produce the expected result as well (I think it has something to do with the escaping of the slash):

![image](https://user-images.githubusercontent.com/4954611/215444453-8c1a31bf-c601-4d9a-9c25-7017c7fc9f1f.jpeg)

**Comment by williamhjcho** [comment]
Hi @Petri-Oosthuizen 

yes you're right, the slashes are being escaped, this was introduced in the previous versions
and if you don't want that behavior, you can either:

 add an escaping prefix (default is `-`) like this:
`{{-date, dateTime(...)}}`

or just turn it off by default by setting your `I18NextOptions.escapeValue` to false.
