### ISSUE TITLE
[ResourceStore]: Caching

### ISSUE THREAD

**Issue by Ahmadre** [williamhjcho/i18next#16]
Officially it's possible to cache translations: https://www.i18next.com/how-to/caching

Is it planned to implement Caching Mechanisms for this package?

It would be great if you can set Remote and Locale Cache Backends.

**Comment by williamhjcho** [comment]
Hey @Ahmadre 

While it's not directly supported by this package, the existing interfaces and methods should allow caching mechanisms to be inserted on the layers you need them to happen.

What is your use case?
One way of doing this (with some caveats) is creating a custom implementation for `LocalizationDataSource`, which is the lowest interface for actual accessing data, it could check a remote service, the local cache, or get the asset default.

**Comment by Ahmadre** [comment]
Actually I solved it with the great implementation of `ResourceStore` and `addNamespace` and `isNamespaceRegistered` :).

Those helped me to implement my own Caching Concept.

I will open another Issue with another Question, where I need a method of ResourceStore.
